spring:
  datasource:
    url: jdbc:sqlserver://ALIAR-PC\SQLEXPRESS:1433;database=monitoring_system
    username: monsys
    password: monsys
    platform: mssql
    initialization-mode: always
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false