spring:
  datasource:
    url: jdbc:sqlserver://DESKTOP-13HAE4Q\SQLEXPRESS:1433;database=monitoring_system
    username: sysmon
    password: sysmon
    platform: mssql
    initialization-mode: always
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false